stages:
  - deploy

deploy:
  stage: deploy
  script:
  - echo "deploy_production"
  - ssh -tt debian@138.195.139.207 << 'HERE'
  - cd /var/www/back-ping-it 
  - git pull origin master 
  - npm install
  - pm2 restart all
  - exit
  tags:
  - deploy